/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205725;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SugorokuTest {
    @Test 
    
}